Test coverage increase
atlp-rwanda/knights-ecomm-be pull request #104
Opened 2024-05-28 18:03 UTC by GSinseswa721

**Description**

This PR is all about increasing the coverage of our project. Currently it had a test coverage of 77% , we have to increase it at least up to 90%. We are going to write tests to cover untested and partially tested areas of the code.

**Description of task to be completed**

- [ ] The test coverage increase at least to 90%.
- [ ] No functionality is broken by the new test.
- [ ] All test pass successfully.

2024-05-30 07:24 UTC, faid-terence commented
@GSinseswa721 and @Ndevu12 
What's the progress ?

2024-05-30 09:32 UTC, Ndevu12 commented
> @GSinseswa721 and @Ndevu12 
> What's the progress ?

We have managed to achieve 81% for now

2024-06-03 10:48 UTC, faid-terence requested changes
@GSinseswa721 and @Ndevu12 
We need  acoverage of 90+%

2024-06-03 12:54 UTC, aimedivin requested changes

2024-06-03 12:54 UTC, aimedivin commented on src/__test__/cart.test.ts
> +});
@Ndevu12 , @GSinseswa721 , please check the 'Order Management Tests' suite starting from line 392 to see if they are written correctly. for ex, test on line 398, 436 (their test names).

2024-06-04 15:52 UTC, maxCastro1 approved these changes

2024-06-06 07:30 UTC, closed without merging