Implement buyer able to leave feedback on products
atlp-rwanda/knights-ecomm-be pull request #107
Opened 2024-05-30 12:19 UTC by UwicyezaG

### Description

This feature will allow buyers to leave feedback on products they have purchased, which will help future buyers to make informed decisions. This feedback will be visible to all users who access the product page, including buyers, vendors, and admins. Buyers will have the capability to create, update, and delete their feedback. Admins will have the ability to view and delete any feedback, while vendors will only be able to view the feedback.

### Functionalities

- Buyers can leave feedback on products they have purchased.
- Buyers can manage the feedback by updating and deleting them.
- All users that view product page.
- Admin management can view and delete any feedback.

### Acceptance Criteria 

- A logged-in buyer can submit feedback on a product.
- Buyers can update or delete their own feedback.
- Feedback is visible to all users who access the product page.
- Admins can view and delete any feedback and Vendor can only view the product.

### Definition of Done

- [ ] Backend API endpoints for creating, updating, viewing, and deleting feedback are implemented and functional.
- [ ] Validation is in place to ensure only logged-in buyers can leave, update, or delete their feedback.
- [ ] Admin controls for managing feedback are implemented.
- [ ] Tests are practiced to ensure the system works correctly and is easy to use.
- [ ] User feedback is collected and used to enhance the feedback system.

2024-05-30 15:32 UTC, elijahladdie approved these changes

2024-05-31 08:53 UTC, elijahladdie approved these changes
LGTM

2024-05-31 09:44 UTC, faid-terence requested changes

2024-05-31 09:44 UTC, faid-terence commented on src/services/feedbackServices/createFeedback.ts
@UwicyezaG and @elijahladdie 
Check if a buyer has bought that product !

2024-05-31 10:50 UTC, elijahladdie approved these changes

2024-05-31 10:50 UTC, elijahladdie commented on src/services/feedbackServices/createFeedback.ts
> +
@faid-terence You mean something like this

2024-05-31 14:43 UTC, faid-terence requested changes

2024-05-31 14:43 UTC, faid-terence commented on src/services/feedbackServices/createFeedback.ts
@UwicyezaG and @elijahladdie 
Remove console.logs

2024-06-01 08:41 UTC, elijahladdie commented on src/services/feedbackServices/createFeedback.ts
Console already removed 🙂

2024-06-01 12:37 UTC, faid-terence approved these changes
Nice Work @UwicyezaG and @elijahladdie !
PR Approved !

2024-06-01 12:37 UTC, merged