Add Jest Testing Setup and Root Route Test
atlp-rwanda/knights-ecomm-be pull request #18
Opened 2024-04-24 10:32 UTC by maxCastro1

This pull request adds the Jest testing setup for our project and includes a test for the root route of our Express application.

Changes include:
1. Setup of Jest and TypeScript dependencies.
2. Configuration of Jest for TypeScript in `jest.config.js`.
3. Creation of `__tests__` directory for unit tests.
4. Addition of test script to `package.json`.
5. A unit test for the root ('/') route of the application.

Testing: 
`npm test`

2024-04-24 11:43 UTC, MC-Knight commented
In my opinion, you should remove the coverage folder, add it to .gitignore, and move it to the corresponding branch. Additionally, you can update the test script to jest --coverage --detectOpenHandles --verbose and --runInBand. For a better test experience.

2024-04-24 11:54 UTC, faid-terence requested changes
@maxCastro1 !
Please create a branch for a chore not from main

2024-04-24 13:20 UTC, elijahladdie requested changes
I think you should consider @MC-Knight comment for removing coverage folder
hint: you can add it in .gitignore

2024-04-24 14:31 UTC, closed without merging

2024-04-27 13:08 UTC, Ndevu12 approved these changes