Setup environment variable example
atlp-rwanda/knights-ecomm-be pull request #38
Opened 2024-04-28 21:43 UTC by UwicyezaG

## This PR focuses on the initial setup of the environment configuration of the project. It includes:
- Implemented environment configuration using dotenv for managing different settings like database connection and production environment

2024-04-28 21:46 UTC, faid-terence requested changes
@UwicyezaG !
Please write a proper PR !

2024-04-29 05:01 UTC, elijahladdie approved these changes

2024-04-29 05:34 UTC, Ndevu12 approved these changes

2024-04-29 06:15 UTC, MC-Knight approved these changes

2024-04-29 06:26 UTC, Calebgisa72 approved these changes

2024-04-29 07:29 UTC, faid-terence approved these changes
Nice Work @UwicyezaG !

2024-04-29 07:29 UTC, merged