adding reset password feature
atlp-rwanda/knights-ecomm-be pull request #54
Opened 2024-05-02 15:14 UTC by elijahladdie

### Acceptance Criteria

- [x] Implement a password reset request API endpoint
- [x] Validate the user's email or account identifier
- [x] Generate and send a secure password reset token (e.g., via email)
- [x] Implement a password reset confirmation API endpoint
- [x] Validate the password reset token
- [x] Update the user's password with a new, securely hashed password
- [x] Implement appropriate error handling and responses
- [x] Implement input sanitization

2024-05-05 07:45 UTC, faid-terence requested changes
@elijahladdie 
Please remove the console.logs !!

2024-05-05 07:45 UTC, faid-terence commented on ormconfig.js
@elijahladdie 
Why to did you turn the loggings to true?

2024-05-05 07:45 UTC, faid-terence commented
@elijahladdie 
Resolve the conflicts !!

2024-05-05 22:00 UTC, faid-terence commented
![Screenshot from 2024-05-05 23-59-57](https://github.com/atlp-rwanda/knights-ecomm-be/assets/122970729/95b00d31-57e1-4ebd-ab69-fb98e288d630)

Add more test for these services

2024-05-06 13:11 UTC, maxCastro1 approved these changes

2024-05-06 19:37 UTC, aimedivin approved these changes

2024-05-06 19:50 UTC, GSinseswa721 approved these changes

2024-05-06 20:59 UTC, faid-terence requested changes

2024-05-06 20:59 UTC, faid-terence commented on .env.example
remove the AUTH_PASSWORD= variable

2024-05-07 06:38 UTC, Calebgisa72 approved these changes

2024-05-07 07:24 UTC, faid-terence approved these changes
Approved! @elijahladdie

2024-05-07 07:24 UTC, merged