Implement user profile update feature
atlp-rwanda/knights-ecomm-be pull request #64
Opened 2024-05-06 01:36 UTC by UwicyezaG

#### What does this PR do?

This PR implements the user profile update feature, which enables users to update their profile information

#### Description of Task to be completed
 ##### Involves:
- Adding a user profile update API endpoint.
- Checking and sanitizing user input for data security.
- Ensuring accurate updates to user profile information in the database.
- Applying input sanitization to prevent security risks.
- Writing unit tests to cover different scenarios.
- Documenting the API endpoint.

#### How should this be manually tested 

`git clone https://github.com/atlp-rwanda/knights-ecomm-be.git`
`cd knights-ecomm-be`
`npm i`
`npm run dev`

2024-05-07 12:39 UTC, faid-terence requested changes
![Screenshot from 2024-05-07 14-38-25](https://github.com/atlp-rwanda/knights-ecomm-be/assets/122970729/96d7f612-25de-4f2c-bca5-b4b11e1a714d)
coverage decreased by 27% .

2024-05-08 12:34 UTC, elijahladdie requested changes
Remove conflicts

2024-05-09 17:24 UTC, maxCastro1 approved these changes

2024-05-09 17:30 UTC, aimedivin approved these changes

2024-05-09 17:33 UTC, faid-terence approved these changes
Great @UwicyezaG !

2024-05-09 17:33 UTC, merged