feat-implement-user-status-update
atlp-rwanda/knights-ecomm-be pull request #65
Opened 2024-05-06 08:55 UTC by Calebgisa72

What does this PR do?
This PR introduces several key features and enhancements to the project with aim to improve user management and security.

Description of Task Completed:

1. User Activation and Deactivation Functionality:
- Implemented activateUser and deactivateUser functions to handle user activation and deactivation processes respectively.
- Utilized an email generator utility with two email templates: one for user activation and another for user deactivation. These templates are invoked within the activateUser and deactivateUser functions to send appropriate emails to users.

2. Middleware for User Status Restriction:
- Developed a middleware to restrict actions for users with a suspended status. This middleware ensures that users with a suspended status cannot perform certain actions within the application.

3. Testing:
- Comprehensive tests have been written to verify the functionality of activateUser, deactivateUser, and the user status restriction middleware.

How should this be manually tested?

- git clone https://github.com/atlp-rwanda/knights-ecomm-be.git
- cd knights-ecomm-be
- git checkout ft-update-user-status
- npm install
- npm run dev
- npm run test

2024-05-06 20:16 UTC, aimedivin approved these changes

2024-05-06 21:19 UTC, MC-Knight approved these changes

2024-05-07 08:10 UTC, maxCastro1 approved these changes

2024-05-07 08:23 UTC, UwicyezaG approved these changes

2024-05-07 08:26 UTC, elijahladdie requested changes
can you rebase with develop please

2024-05-07 08:42 UTC, aimedivin approved these changes

2024-05-07 08:51 UTC, MC-Knight approved these changes

2024-05-07 08:57 UTC, faid-terence approved these changes
Nice Work @Calebgisa72 !

2024-05-07 08:57 UTC, merged