google authentication
atlp-rwanda/knights-ecomm-be pull request #84
Opened 2024-05-15 23:36 UTC by GSinseswa721

**What does this PR do?**

This PR is all about Google OAuth authentication for user sign in.

It configures Passport.js to utilize the Google OAuth strategy, allowing users to log in using their Google accounts.

**Description of Task to be completed**

Configuring Passport.js with Google OAuth strategy.
Implement routes for Google sign-in and callback handling.
Authenticate users using Google profile information.

**How should this be manually tested?**

```
npm run dev

```

2024-05-16 19:51 UTC, faid-terence commented
@GSinseswa721 resolve the conflict and tests are decreasing !

2024-05-17 12:40 UTC, elijahladdie approved these changes

2024-05-19 16:43 UTC, maxCastro1 approved these changes

2024-05-19 22:21 UTC, faid-terence requested changes

2024-05-19 22:21 UTC, faid-terence commented on src/utils/auth.ts
@GSinseswa721 remove the console.log(".................")

2024-05-19 22:21 UTC, faid-terence commented on src/routes/ProductRoutes.ts
@GSinseswa721 Remove as any on middlewares , using any we're not utilising power of typescript.

2024-05-19 22:21 UTC, faid-terence commented on src/routes/ProductRoutes.ts
@GSinseswa721 
Remove as any on middlewares !

2024-05-20 09:11 UTC, faid-terence requested changes

2024-05-20 09:11 UTC, faid-terence commented on src/routes/ProductRoutes.ts
@GSinseswa721 remove unnecessary commented codes.

2024-05-20 10:45 UTC, faid-terence approved these changes
Nice Work @GSinseswa721 !

2024-05-20 10:45 UTC, merged