Ft product search
atlp-rwanda/knights-ecomm-be pull request #87
Opened 2024-05-16 11:33 UTC by GSinseswa721

**Description**

This PR is all about the implementation of the product search, so that the buyer could be able to search inside the e-commerce.

**Functionality**

- Searching the product by using name.
- Using filtering and sorting to retrieve data from database.
- Implementation of pagination for managing big result.

2024-05-16 14:35 UTC, faid-terence commented
@GSinseswa721 Please before starting we need to see your implementation plan !

2024-05-17 15:12 UTC, Calebgisa72 approved these changes

2024-05-19 16:45 UTC, maxCastro1 approved these changes

2024-05-19 22:25 UTC, faid-terence requested changes

2024-05-19 22:25 UTC, faid-terence commented on src/routes/ProductRoutes.ts
@GSinseswa721 
Remove as any on middlwares

2024-05-19 22:25 UTC, faid-terence commented on src/utils/auth.ts
@GSinseswa721 
Remove console.log("......................")s in the project

2024-05-20 10:57 UTC, faid-terence commented
@GSinseswa721 
Progress on this PR ?

2024-05-20 14:46 UTC, faid-terence commented
@GSinseswa721 Resolve the conflicts and increase the coverage as well

2024-05-21 07:27 UTC, Ndevu12 approved these changes

2024-05-21 13:18 UTC, UwicyezaG approved these changes

2024-05-21 13:26 UTC, elijahladdie approved these changes

2024-05-21 13:32 UTC, faid-terence approved these changes
Nice Work @GSinseswa721 !

2024-05-21 13:32 UTC, merged