implementing order tracking and order managment issue
atlp-rwanda/knights-ecomm-be pull request #94
Opened 2024-05-22 15:06 UTC by UwicyezaG

2024-05-22 19:30 UTC, faid-terence commented
@UwicyezaG and @elijahladdie Rename the PR !
Follow best PR naming conventions

2024-05-24 07:40 UTC, faid-terence commented
@UwicyezaG and @elijahladdie 
What's the progres ??

2024-05-24 07:40 UTC, faid-terence commented
Too many commit messages squash them we need only one commit message !

2024-05-24 07:45 UTC, faid-terence commented
Follow this https://github.com/atlp-rwanda/engineering-playbook/wiki/3.-Pull-Request for PR naming

2024-05-25 20:19 UTC, faid-terence commented
@elijahladdie and @UwicyezaG 
What are the updates on this PR ?

2024-05-26 17:03 UTC, elijahladdie approved these changes

2024-05-26 17:10 UTC, faid-terence commented
@UwicyezaG  and @elijahladdie 
Test coverage decreased by 2.9% can you increase it by adding more test cases !

2024-05-26 17:17 UTC, faid-terence requested changes
@UwicyezaG  and @elijahladdie 
Apply the feedbacks

2024-05-26 17:17 UTC, faid-terence commented on src/entities/User.ts
@elijahladdie 
Please avoid using `any` in typescript , please define order interface

2024-05-26 17:17 UTC, faid-terence commented on src/utils/index.ts
@UwicyezaG  and @elijahladdie 
amount should be number not any !

2024-05-26 17:17 UTC, faid-terence commented on src/utils/sendOrderMail.ts
orderDate should be type `Date` not any

2024-05-26 17:17 UTC, faid-terence commented on src/utils/sendOrderMailUpdated.ts
Remove any

2024-05-26 17:43 UTC, Ndevu12 approved these changes

2024-05-26 18:00 UTC, elijahladdie commented on src/utils/sendOrderMail.ts
Feedback solved @faid-terence !

2024-05-26 18:55 UTC, aimedivin requested changes

2024-05-26 18:55 UTC, aimedivin commented on src/entities/User.ts
> +  accountBalance!: number;
@elijahladdie , @UwicyezaG How this field will get it's value

2024-05-26 18:55 UTC, aimedivin commented on src/services/orderServices/updateOrderService.ts
> +            if (orderStatus !== undefined && order.orderStatus !== orderStatus) {
@elijahladdie , @UwicyezaG , Before updating the order status, could you please check if the order has been marked as "received" first? It doesn't make sense for a buyer to update an order to "canceled" after they have already confirmed that they received it.

2024-05-26 19:01 UTC, aimedivin requested changes

2024-05-26 19:01 UTC, aimedivin commented on src/services/orderServices/updateOrderService.ts
> +    const { orderStatus } = req.body;
@UwicyezaG , @elijahladdie Can you check if provided orderStatus is among the ones defined as possible value in "orderStatus" field

2024-05-27 05:52 UTC, aimedivin approved these changes

2024-05-27 05:53 UTC, MC-Knight approved these changes

2024-05-27 07:48 UTC, faid-terence approved these changes
PR Appproved @UwicyezaG and @elijahladdie !

2024-05-27 07:49 UTC, merged