ft<discount-coupon> adding discount coupon feature PR
atlp-rwanda/knights-ecomm-be pull request #95
Opened 2024-05-22 15:14 UTC by Ndevu12

This PR introduces the discount coupon feature, allowing vendors to create, manage, and apply discount coupons to customer orders. Key changes include database schema updates, new API endpoints, and comprehensive testing.

## Changes Made

1. Database Design

Created a coupons table with columns for ID, code, discount type/value, expiration date, usage counts, vendor ID, product IDs, and timestamps.
Updated vendors, customers, orders, and customerCoupons tables for relationships with coupons.

## API Endpoints

Create Coupon: POST /api/coupons
Apply Coupon: POST /api/checkout/apply-coupon
Get Vendor Coupons: GET /api/vendors/:vendorId/coupons

## Testing

Added unit tests for coupon functionality.
Added integration tests for API endpoints.

## Documentation

Updated API documentation with new coupon endpoints.

## How to Test
```bash
Run Migrations
```

Apply new database migrations:

```bash
npm run migrate
```

## Run Tests

Execute the test suite:
```bash
npm test
```

2024-05-22 19:29 UTC, faid-terence commented
@Ndevu12 
This is not a proper PR Title , please rename it

2024-05-23 09:39 UTC, Ndevu12 commented
@faid-terence corrected

2024-05-23 15:40 UTC, Calebgisa72 reviewed
In the coupon entity check on adding a field to keep track of the number of times the coupon has been used, it can start by zero and be incremented by one as a buyer use that token

2024-05-24 13:19 UTC, faid-terence commented
![Screenshot from 2024-05-24 15-17-39](https://github.com/atlp-rwanda/knights-ecomm-be/assets/122970729/c2278650-03fa-4bbf-b275-66715487b35d)
@Ndevu12 Why did you delete these tests ??

2024-05-24 13:31 UTC, faid-terence requested changes
@Ndevu12 Please get all tests back , you deleted them !!!

2024-05-24 13:31 UTC, faid-terence commented on src/__test__/cart.test.test.ts
@Ndevu12 
Why did you deleted these tests ?

2024-05-24 13:31 UTC, faid-terence commented on src/__test__/getProduct.test.ts
@Ndevu12 
Why did you deleted these tests ?

2024-05-24 13:31 UTC, faid-terence commented on src/__test__/userStatus.test.ts
@Ndevu12 
Why did you deleted these tests ?

2024-05-24 13:31 UTC, faid-terence commented on src/__test__/vendorProduct.test.ts
@Ndevu12 
Why did you deleted these tests ?

2024-05-24 13:31 UTC, faid-terence commented on src/__test__/wishList.test.ts
@Ndevu12 
Why did you deleted these tests ?

2024-05-24 16:36 UTC, Ndevu12 commented
> @Ndevu12 Please get all tests back , you deleted them !!!

@faid-terence Sorry for this mistake. I can't say that I didn't do it by intention. The reason for the deletion of these tests is that I was running out of time and I had been fixing the errors they had around 30 minutes. so, because I had an exam at 3:00PM. I had to do quick things so, that I can attend the exam and all others who depend on this PR can progress on their projects. If needed, I can work the tests. Am ready. Also I have managed to write API endpoints documentation

2024-05-24 20:21 UTC, faid-terence commented
@Ndevu12 Understood but never do that again , it's selfish removing other people's work to keep yours 
Please work together as a team !

2024-05-24 22:58 UTC, Ndevu12 commented
> @Ndevu12 Understood but never do that again , it's selfish removing other people's work to keep yours 
> Please work together as a team !
> 
> 

- @faid-terence noted Sir, won't happen again, but I was trying to not keeping others not working on their works. But before any other things I will ask for a permission even if it will be urgent. Thanks for your understanding. Best regards.

2024-05-25 10:55 UTC, Ndevu12 commented
> @Ndevu12 Please get all tests back , you deleted them !!!

@faid-terence Now, All tests are added back!

2024-05-25 15:25 UTC, aimedivin approved these changes

2024-05-25 17:19 UTC, faid-terence approved these changes
PR Approved @Ndevu12 !

2024-05-25 17:35 UTC, Ndevu12 commented
> PR Approved @Ndevu12 !

@faid-terence thanks for the assistance and awareness!

2024-05-25 17:43 UTC, MC-Knight approved these changes

2024-05-25 17:43 UTC, UwicyezaG approved these changes

2024-05-25 17:48 UTC, aimedivin approved these changes

2024-05-25 18:21 UTC, Calebgisa72 approved these changes

2024-05-25 20:15 UTC, merged